config/routes.rb
Dynacan::Application.routes.draw do
  resources :drawings

  resources :parts

  devise_for :users
  resources :roles

  root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user.role.permissions.each do |permission|
      if permission.subject_class == "all"
        can permission.action.to_sym, permission.subject_class.to_sym
      else
        can permission.action.to_sym, permission.subject_class.constantize
      end
    end
  end
end

app/models/drawing.rb
class Drawing < ActiveRecord::Base
  attr_accessible :sheet_number, :part_id
  belongs_to :part
end

app/models/part.rb
class Part < ActiveRecord::Base
  attr_accessible :name
  has_many :drawings
  has_many :plans
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  attr_accessible :subject_class, :action, :name
end

app/models/role.rb
class Role < ActiveRecord::Base

  attr_accessible :name

  has_many :users
  has_and_belongs_to_many :permissions

  validates :name, presence: true, uniqueness: true

  def set_permissions(permissions)
    permissions.each do |id|
      permission = Permission.find(id)
      self.permissions << permission
      case permission.subject_class
      when "Part"
        case permission.action
        when "create"
          self.permissions << Permission.where(subject_class: "Drawing", action: "create")
        when "update"
          self.permissions << Permission.where(subject_class: "Drawing", action: ["update", "destroy"])
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_id, :name

  belongs_to :role

  def super_admin?
    self.role.name == "Super Admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = "Access denied. You are not authorized to access the requested page."
    redirect_to root_path and return
  end

  protected

  def self.permission
    return name = self.name.gsub('Controller','').singularize.split('::').last.constantize.name rescue nil
  end

  def current_ability
    @current_ability ||= Ability.new(current_user)
  end

  def load_permissions
    @current_permissions = current_user.role.permissions.collect{|i| [i.subject_class, i.action]}
  end

end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
  
  before_filter :authenticate_user!
  load_and_authorize_resource
  before_filter :load_permissions

  def index
    @drawings = Drawing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drawings }
    end
  end

  def new
    @parts = Part.all
    @drawing = Drawing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @drawing }
    end
  end

  def create
    @parts = Part.all
    @drawing = Drawing.new(params[:drawing])

    respond_to do |format|
      if @drawing.save
        format.html { redirect_to @drawing, notice: 'Drawing was successfully created.' }
        format.json { render json: @drawing, status: :created, location: @drawing }
      else
        format.html { render action: "new" }
        format.json { render json: @drawing.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @drawing = Drawing.find(params[:id])
    @drawing.destroy

    respond_to do |format|
      format.html { redirect_to drawings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_permissions

  def index
  end

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource
  before_filter :load_permissions

  def index
    @parts = Part.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parts }
    end
  end

  def show
    @part = Part.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @part }
    end
  end

  def new
    @part = Part.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @part }
    end
  end

  def edit
    @part = Part.find(params[:id])
  end

  def create
    @part = Part.new(params[:part])

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render json: @part, status: :created, location: @part }
      else
        format.html { render action: "new" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @part = Part.find(params[:id])

    respond_to do |format|
      if @part.update_attributes(params[:part])
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @part = Part.find(params[:id])
    @part.destroy

    respond_to do |format|
      format.html { redirect_to parts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_super_admin?

  def index
    @roles = Role.all.keep_if{|i| i.name != "Super Admin"}
  end

  def show
    @role = Role.find(params[:id])
    @permissions = @role.permissions
  end

  def edit
    @role = Role.find(params[:id])
    @permissions = Permission.all.keep_if{|i| ["Part"].include? i.subject_class}.compact
    @role_permissions = @role.permissions.collect{|p| p.id}
  end

  def update
    @role = Role.find(params[:id])
    @role.permissions = []
    @role.set_permissions(params[:permissions]) if params[:permissions]
    if @role.save
      redirect_to roles_path and return
    end
    @permissions = Permission.all.keep_if{|i| ["Part"].include? i.subject_class}.compact
    render 'edit'
  end

  private

  def is_super_admin?
    redirect_to root_path and return unless current_user.super_admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drawings_helper.rb
module DrawingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/drawings/_form.html.haml
= form_for @drawing do |f|
  - if @drawing.errors.any?
    #error_explanation
      %h2= "#{pluralize(@drawing.errors.count, "error")} prohibited this drawing from being saved:"
      %ul
        - @drawing.errors.full_messages.each do |msg|
          %li= msg
  = f.select :part_id, @parts.collect{|i| [i.name, i.id]}
  = f.label :sheet_number
  = f.text_box :sheet_number

  .actions
    = f.submit 'Save'

app/views/drawings/edit.html.haml
%h1 Editing drawing

= render 'form'

= link_to 'Show', @drawing
\|
= link_to 'Back', drawings_path

app/views/drawings/index.html.haml
%h1 Listing drawings

%table
  %tr
    %th
    %th
    %th

  - @drawings.each do |drawing|
    %tr
      %td= link_to 'Show', drawing
      %td= link_to 'Edit', edit_drawing_path(drawing)
      %td= link_to 'Destroy', drawing, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Drawing', new_drawing_path

app/views/drawings/new.html.haml
%h1 New drawing

= render 'form'

= link_to 'Back', drawings_path

app/views/drawings/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_drawing_path(@drawing)
\|
= link_to 'Back', drawings_path

app/views/home/index.html.haml
%br
%br
%br
%br
= link_to "Roles", roles_path if current_user.super_admin?
%br
= link_to "Parts", parts_path if @current_permissions.include?(["Part", "index"])
%br

app/views/layouts/application.html.haml
%html
%head
  %title Dynacan
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
  - if user_signed_in?
    = link_to "Sign out", destroy_user_session_path, :method => :delete
    = current_user.name.titleize
    %br
    %br
    = link_to "Home", root_path
%body
  = yield 

app/views/parts/_form.html.haml
= form_for @part do |f|
  - if @part.errors.any?
    #error_explanation
      %h2= "#{pluralize(@part.errors.count, "error")} prohibited this part from being saved:"
      %ul
        - @part.errors.full_messages.each do |msg|
          %li= msg
  = f.label :name
  = f.text_field :name

  .actions
    = f.submit 'Save'

app/views/parts/edit.html.haml
%h1 Editing part

= render 'form'

= link_to 'Show', @part
\|
= link_to 'Back', parts_path

app/views/parts/index.html.haml
%h1 Listing parts

%table
  %tr
    %th
    %th
    %th

  - @parts.each do |part|
    %tr
      %td= part.name
      %td= link_to 'Show', part if @current_permissions.include?(["Part", "show"])
      %td= link_to 'Edit', edit_part_path(part) if @current_permissions.include?(["Part", "update"])
      %td= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } if @current_permissions.include?(["Part", "destroy"])

%br

= link_to 'New Part', new_part_path if @current_permissions.include?(['Part', 'create'])

app/views/parts/new.html.haml
%h1 New part

= render 'form'

= link_to 'Back', parts_path

app/views/parts/show.html.haml
%p#notice= notice
%br
= @part.name

= link_to 'Edit', edit_part_path(@part)
\|
= link_to 'Back', parts_path

app/views/roles/edit.html.haml
%div.row
  %div.span16
    = form_for( @role, :url => role_path, :method => :put) do |f|
      %fieldset
        %legend Role
        %br
        = @role.name
        %br
        Permissions
        %br
        %table
          %tr
            %th Class
            %th Action
            %th #{check_box_tag 'main', 0, false}
          - @permissions.each do |permission|
            %tr
              %td= permission.subject_class
              %td= permission.action
              %td= check_box_tag 'permissions[]', permission.id, @role_permissions.include?(permission.id), {array: true, class: "check_box"} 

        %div.span16.offset2
          %div.clearfix
            = f.submit "Update", :class => 'btn primary'
            = link_to 'Cancel', roles_path

app/views/roles/index.html.haml
%h1 Super Admin: Listing Roles

%table
  %tr
    %th Name
    %th
    %th

  - @roles.each do |role|
    %tr
      %td= role.name
      %td= link_to 'Show', role
      %td= link_to 'Edit', edit_role_path(role)

%br

app/views/roles/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @role.name

Permissions
%table
  %tr
    %th Class
    %th Action

  - @permissions.each do |permission|
    %tr
      %td= permission.subject_class
      %td= permission.action

= link_to 'Back', roles_path